stages:
    - style
    - test

variables:
    POSTGRES_PASS: password
    POSTGRES_HOST_AUTH_METHOD: trust

style-job:
    stage: style
    image: python:3.10-alpine
    before_script:
        - pip install tox
    script:
        - tox -e flake8

test-job:
    stage: test
    needs: ["style-job"]
    image: python:3.10

    services:
        - name: kartoza/postgis:latest
          alias: postgres

    before_script:
        - export POSTGRES_PASSWORD=$POSTGRES_PASS
        - apt-get update
        - apt-get install -y python3-dev build-essential postgresql-client
        - pip install tox

    script:
        - tox -e py310-tests

    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
