services:
    prefect-server:
        image: prefecthq/prefect:3-latest
        command: prefect server start
        restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
        ports:
            - '4200:4200'
        environment:
            - PREFECT_SERVER_API_HOST=0.0.0.0
            - PREFECT_UI_API_URL=http://localhost:4200/api
            - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:password@prefect-postgres:5433/prefect
        depends_on:
            - prefect-postgres
        networks:
            - hermesnet

    prefect-postgres:
        image: postgres:latest
        restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
        ports:
            - '5433:5433'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=prefect
            - PGPORT=5433
        volumes:
            - prefectdb:/var/lib/postgresql/data
        networks:
            - hermesnet

volumes:
    prefectdb: {}
networks:
    hermesnet: {}
