services:
    postgres:
        environment:
            - POSTGRES_USER
            - POSTGRES_DB
            - POSTGRES_PASS=${POSTGRES_PASSWORD}
        image: kartoza/postgis:latest
        restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
        ports:
            - '0.0.0.0:${POSTGRES_PORT:-5434}:5432'
        volumes:
            - hermesdb:/var/lib/postgresql/data
        networks:
            - hermesnet

    webservice:
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PASSWORD
            - POSTGRES_PORT=${POSTGRES_PORT:-5434}
            - POSTGRES_USER
            - POSTGRES_DB
        build: .
        depends_on:
            - postgres
        restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
        ports:
            - '0.0.0.0:${DOCKER_WEB_PORT:-8000}:8000'
        networks:
            - hermesnet

volumes:
    hermesdb: {}
networks:
    hermesnet: {}
