services:
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start
    ports:
      - "4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:password@prefect-postgres:5433/prefect
    depends_on:
      - prefect-postgres

  prefect-postgres:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prefect
      - PGPORT=5433
    volumes:
      - prefectdb:/var/lib/postgresql/data

  hermes-postgres:
    image: kartoza/postgis:latest
    ports:
      - "5434:5432"
    env_file: .env
    volumes:
      - hermesdb:/var/lib/postgresql/data

volumes:
  prefectdb:
  hermesdb: