services:
    postgres:
        image: kartoza/postgis:latest
        ports:
            - '0.0.0.0:${POSTGRES_PORT:-5432}:5432'
        env_file: .env
        volumes:
            - hermesdb:/var/lib/postgresql
        networks:
            - backend

    webservice:
        env_file: '.env'
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres
        build: .
        restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
        ports:
            - '0.0.0.0:${DOCKER_WEB_PORT:-8000}:8000'
        networks:
            - backend

volumes:
    hermesdb: {}
networks:
    backend: {}
