services:
    postgres:
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASS=${POSTGRES_PASSWORD}
        image: kartoza/postgis:latest
        restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
        ports:
            - 0.0.0.0:${POSTGRES_PORT:-5434}:5432
        volumes:
            - hermesdb:/var/lib/postgresql/data
            - ${POSTGRES_PGCONF:-./alembic/postgresql.conf}:/settings/extra.conf
        networks:
            - hermesnet

    webservice:
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres
        build: .
        depends_on:
            - postgres
        restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
        ports:
            - 0.0.0.0:${DOCKER_WEB_PORT:-8000}:8000
        networks:
            - hermesnet

volumes:
    hermesdb: {}
networks:
    hermesnet: {}
