# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Dec  9 12:37:28 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setFixedSize(450, 300)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.projectSummaryLabel = QtGui.QLabel(self.centralWidget)
        self.projectSummaryLabel.setGeometry(QtCore.QRect(30, 20, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.projectSummaryLabel.setFont(font)
        self.projectSummaryLabel.setObjectName(_fromUtf8("projectSummaryLabel"))
        self.projectNameLabel = QtGui.QLabel(self.centralWidget)
        self.projectNameLabel.setGeometry(QtCore.QRect(30, 50, 211, 16))
        self.projectNameLabel.setObjectName(_fromUtf8("projectNameLabel"))
        self.startDateLabel = QtGui.QLabel(self.centralWidget)
        self.startDateLabel.setGeometry(QtCore.QRect(30, 70, 211, 16))
        self.startDateLabel.setObjectName(_fromUtf8("startDateLabel"))
        self.endDateLabel = QtGui.QLabel(self.centralWidget)
        self.endDateLabel.setGeometry(QtCore.QRect(30, 90, 211, 16))
        self.endDateLabel.setObjectName(_fromUtf8("endDateLabel"))
        self.seismicEventCountLabel = QtGui.QLabel(self.centralWidget)
        self.seismicEventCountLabel.setGeometry(QtCore.QRect(30, 120, 261, 16))
        self.seismicEventCountLabel.setObjectName(_fromUtf8("seismicEventCountLabel"))
        self.exposureDataLabel = QtGui.QLabel(self.centralWidget)
        self.exposureDataLabel.setGeometry(QtCore.QRect(30, 140, 261, 16))
        self.exposureDataLabel.setObjectName(_fromUtf8("exposureDataLabel"))
        self.boreholeDataLabel = QtGui.QLabel(self.centralWidget)
        self.boreholeDataLabel.setGeometry(QtCore.QRect(30, 160, 261, 16))
        self.boreholeDataLabel.setObjectName(_fromUtf8("boreholeDataLabel"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 598, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuOpen_Recent = QtGui.QMenu(self.menu_File)
        self.menuOpen_Recent.setObjectName(_fromUtf8("menuOpen_Recent"))
        self.menuSimulation = QtGui.QMenu(self.menuBar)
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        self.menuWindow = QtGui.QMenu(self.menuBar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setFloatable(False)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.statusBar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusBar)
        self.actionImport_Seismic_Data = QtGui.QAction(MainWindow)
        self.actionImport_Seismic_Data.setObjectName(_fromUtf8("actionImport_Seismic_Data"))
        self.actionView_Data = QtGui.QAction(MainWindow)
        self.actionView_Data.setObjectName(_fromUtf8("actionView_Data"))
        self.actionStart_Simulation = QtGui.QAction(MainWindow)
        self.actionStart_Simulation.setObjectName(_fromUtf8("actionStart_Simulation"))
        self.actionPause_Simulation = QtGui.QAction(MainWindow)
        self.actionPause_Simulation.setObjectName(_fromUtf8("actionPause_Simulation"))
        self.actionStop_Simulation = QtGui.QAction(MainWindow)
        self.actionStop_Simulation.setObjectName(_fromUtf8("actionStop_Simulation"))
        self.actionShow_3D = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar-buttons/images/view-3d-toolbar-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_3D.setIcon(icon)
        self.actionShow_3D.setObjectName(_fromUtf8("actionShow_3D"))
        self.actionImport_Hydraulic_Data = QtGui.QAction(MainWindow)
        self.actionImport_Hydraulic_Data.setObjectName(_fromUtf8("actionImport_Hydraulic_Data"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionForecasts = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar-buttons/images/forecast-window-toolbar-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForecasts.setIcon(icon1)
        self.actionForecasts.setObjectName(_fromUtf8("actionForecasts"))
        self.actionSimulation = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar-buttons/images/simulate-toolbar-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimulation.setIcon(icon2)
        self.actionSimulation.setObjectName(_fromUtf8("actionSimulation"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setEnabled(True)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionTimeline = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar-buttons/images/timeline-window-toolbar-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimeline.setIcon(icon3)
        self.actionTimeline.setObjectName(_fromUtf8("actionTimeline"))
        self.actionScenario = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar-buttons/images/scenario-toolbar-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScenario.setIcon(icon4)
        self.actionScenario.setObjectName(_fromUtf8("actionScenario"))
        self.menu_File.addAction(self.actionNew_Project)
        self.menu_File.addAction(self.actionOpen_Project)
        self.menu_File.addAction(self.menuOpen_Recent.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSettings)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionImport_Seismic_Data)
        self.menu_File.addAction(self.actionImport_Hydraulic_Data)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionView_Data)
        self.menuSimulation.addAction(self.actionStart_Simulation)
        self.menuSimulation.addAction(self.actionPause_Simulation)
        self.menuSimulation.addAction(self.actionStop_Simulation)
        self.menuWindow.addAction(self.actionShow_3D)
        self.menuWindow.addAction(self.actionForecasts)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuSimulation.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.mainToolBar.addAction(self.actionScenario)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSimulation)
        self.mainToolBar.addAction(self.actionForecasts)
        self.mainToolBar.addAction(self.actionShow_3D)
        self.mainToolBar.addAction(self.actionTimeline)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ATLS", None))
        self.projectSummaryLabel.setText(_translate("MainWindow", "Project Summary", None))
        self.projectNameLabel.setText(_translate("MainWindow", "No Project Loaded", None))
        self.startDateLabel.setText(_translate("MainWindow", "Starts: -", None))
        self.endDateLabel.setText(_translate("MainWindow", "Ends: -", None))
        self.seismicEventCountLabel.setText(_translate("MainWindow", "0 Seismic Events", None))
        self.exposureDataLabel.setText(_translate("MainWindow", "No exposure data available", None))
        self.boreholeDataLabel.setText(_translate("MainWindow", "No borehole data available", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuOpen_Recent.setTitle(_translate("MainWindow", "Open Recent", None))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation", None))
        self.menuWindow.setTitle(_translate("MainWindow", "Window", None))
        self.actionImport_Seismic_Data.setText(_translate("MainWindow", "&Import Seismic Data...", None))
        self.actionView_Data.setText(_translate("MainWindow", "View Data", None))
        self.actionStart_Simulation.setText(_translate("MainWindow", "Start Simulation", None))
        self.actionPause_Simulation.setText(_translate("MainWindow", "Pause Simulation", None))
        self.actionStop_Simulation.setText(_translate("MainWindow", "Stop Simulation", None))
        self.actionShow_3D.setText(_translate("MainWindow", "3D View", None))
        self.actionImport_Hydraulic_Data.setText(_translate("MainWindow", "Import Hydraulic Data...", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "&Open Project...", None))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project...", None))
        self.actionForecasts.setText(_translate("MainWindow", "Forecasts", None))
        self.actionSimulation.setText(_translate("MainWindow", "Simulation", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))
        self.actionTimeline.setText(_translate("MainWindow", "Timeline", None))
        self.actionTimeline.setToolTip(_translate("MainWindow", "Show Timeline", None))
        self.actionScenario.setText(_translate("MainWindow", "Scenario", None))
        self.actionScenario.setToolTip(_translate("MainWindow", "Compute Scenario", None))

import images_rc
