---
# RT-RAMSIS Application Settings Template
#
# These are settings that are specific to the application instance and define
# global parameters which are independent of the currently loaded project.
#
# To use this file, rename it to settings.yml and copy it to an appropriate
# location. RT-RAMSIS will look for it in the cwd as well as in all typical
# platform specific application configuration locations (see AppConfigLocation
# at https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum).

# launch mode
launch_mode: 'lab'  # one of: 'lab', 'real-time'

# Application DB connection information
database:
  name: ramsis
  password: ramsis
  url: postgresql://localhost:5433
  user: ramsis

# simulation settings
simulation:
  max_speed: False
  speed: 1000  # Speed up factor if max_speed is false

env:
  load_environment_cmd: ""

# idempotency_id and labels should both be set to something unique when installing ramsis in a new location.
#
# The following id will be used to distinguish prefect flow runs from
# those being run in different locations, so that a forecast id that is
# the same on two different db's will create two different flow runs.
# It will also be used to uniquely define the registered flow.
idempotency_id: "local_run_"
# The same label should be on the prefect agent and the flow run
# As the code run will be on the same machine as that of
# the agent.
project: "RAMSIS"
label: "my_local"
data_dir: "/home/sarsonl/haz_data"
