CREATE INDEX idx_eventobservation_time_value ON eventobservation USING BRIN (time_value);
CREATE INDEX idx_eventobservation_time_value ON eventobservation USING BRIN (time_value);
CREATE INDEX idx_seismicevent_modelresult_oid ON seismicevent (modelresult_oid);
CREATE INDEX idx_modelresult_modelrun_oid ON modelresult (modelrun_oid);
CREATE INDEX idx_modelrun_forecast_oid ON modelrun (forecast_oid);
CREATE INDEX idx_modelrun_modelconfig_oid ON modelrun (modelconfig_oid);
CREATE INDEX idx_forecast_forecastseries_oid ON forecast (forecastseries_oid);
CREATE INDEX idx_forecast_starttime ON forecast USING BRIN (starttime);
CREATE INDEX idx_forecast_endtime ON forecast USING BRIN (endtime);
CREATE INDEX idx_modelresult_oid ON modelresult(oid);
SET work_mem = '256MB';
SET maintenance_work_mem = '512MB';